name: Deploy Nginx

on:
  workflow_dispatch 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'  # Use the latest version of kubectl

      - name: Deploy Nginx
        run: |
          kubectl create deployment nginx --image=nginx:latest --port=80
          kubectl expose deployment nginx --type=LoadBalancer --port=80 --target-port=80

      - name: Verify deployment
        run: |
          kubectl get pods
